Clean up users api mocking and usage

diff --git a/scripts/actions/test b/scripts/actions/test
--- a/scripts/actions/test
+++ b/scripts/actions/test
@@ -9,17 +9,6 @@
 # See https://github.com/nektos/act
 #
 
-# Set default profile
-profile="consensus-networks-dev"
-
-if [ ${PROFILE+x} ]; then
-    echo "PROFILE is set to '$PROFILE'"
-    profile=$PROFILE
-else
-    export PROFILE="$profile"
-    echo "PROFILE is not set, using default profile $PROFILE"
-fi
-
 # Get args
 while getopts w: flag
 do
@@ -28,19 +17,45 @@ do
     esac
 done
 
-echo "👾 Creating environment for '$profile'"
+if [ -z "$workflow" ]; then
+    echo "⚠️ Workflow is not set – please specify as -w workflow-to-test (i.e. -w push)"
+    exit 1
+fi
+
+# Get variables from root .env
+export $(xargs < .env)
+
+if [ -z "$SLACK_WEBHOOK_URL" ]; then
+    echo "⚠️ SLACK_WEBHOOK_URL is not set – please set a SLACK_WEBHOOK_URL in the root .env file"
+    exit 1
+fi
 
 # From .env
 SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
 
-# From AWS CLI
-aws_access_key_id=$(aws configure get aws_access_key_id --profile $profile)
-aws_secret_access_key=$(aws configure get aws_secret_access_key --profile $profile)
+# Set default profile
+profile="consensus-networks-dev"
+
+if [ ${PROFILE+x} ]; then
+    echo "PROFILE is set to '$PROFILE'"
+    profile=$PROFILE
+else
+    export PROFILE="$profile"
+    echo "PROFILE is not set, using default profile '$PROFILE'"
+fi
+
+export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile $profile)
+export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile $profile)
+
+if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+    echo "🙈 Could not find AWS credentials for profile '$profile'"
+    exit 1
+fi
 
 # Run selected workflow
 echo "🚀 Running $workflow workflow"
 act $workflow \
 --rebuild \
---secret AWS_ACCESS_KEY_ID=$aws_access_key_id \
---secret AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
+--secret AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+--secret AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
 --verbose
