Add copy changes

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -55,86 +55,86 @@ jobs:
       - name: Build and deploy email templates
         run: npm run deploy:templates
 
-      - name: Set deployment outputs
-        run: |
-          export "STACK_KEY=${PROJECT^}${SERVICE^}Stack${STAGE^}"
-          export "DNS_KEY=${PROJECT^}${SERVICE^}DnsName${STAGE^}"
-          export "ARN_KEY=${PROJECT^}${SERVICE^}StackId${STAGE^}"
-          echo "WEBSITE_DNS=$(cat cdk-outputs.json | jq -r --arg stack_key "$STACK_KEY" --arg dns_key "$DNS_KEY" '.[$stack_key][$dns_key]')" >> $GITHUB_ENV
-          echo "WEBSITE_ARN=$(cat cdk-outputs.json | jq -r --arg stack_key "$STACK_KEY" --arg arn_key "$ARN_KEY" '.[$stack_key][$arn_key]')" >> $GITHUB_ENV
-        env:
-          SERVICE: website
+      # - name: Set deployment outputs
+      #   run: |
+      #     export "STACK_KEY=${PROJECT^}${SERVICE^}Stack${STAGE^}"
+      #     export "DNS_KEY=${PROJECT^}${SERVICE^}DnsName${STAGE^}"
+      #     export "ARN_KEY=${PROJECT^}${SERVICE^}StackId${STAGE^}"
+      #     echo "WEBSITE_DNS=$(cat cdk-outputs.json | jq -r --arg stack_key "$STACK_KEY" --arg dns_key "$DNS_KEY" '.[$stack_key][$dns_key]')" >> $GITHUB_ENV
+      #     echo "WEBSITE_ARN=$(cat cdk-outputs.json | jq -r --arg stack_key "$STACK_KEY" --arg arn_key "$ARN_KEY" '.[$stack_key][$arn_key]')" >> $GITHUB_ENV
+      #   env:
+      #     SERVICE: website
 
-      - name: Select success emoji
-        if: ${{ success() }}
-        run: echo 'EMOJI=:rocket:' >> $GITHUB_ENV
+      # - name: Select success emoji
+      #   if: ${{ success() }}
+      #   run: echo 'EMOJI=:rocket:' >> $GITHUB_ENV
 
-      - name: Select failure emoji
-        if: ${{ failure() }}
-        run: echo 'EMOJI=:see_no_evil:' >> $GITHUB_ENV
+      # - name: Select failure emoji
+      #   if: ${{ failure() }}
+      #   run: echo 'EMOJI=:see_no_evil:' >> $GITHUB_ENV
 
-      - name: Notify slack
-        if: ${{ success() || failure() }}
-        uses: slackapi/slack-github-action@v1.18.0
-        with:
-          payload: |
-            {
-              "blocks": [
-                {
-                  "type": "header",
-                  "text": {
-                    "type": "plain_text",
-                    "text": ":construction: Development Deployment → :space_invader: Casimir"
-                  }
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Branch* · <https://github.com/${{ github.repository }}/tree/${{ env.BRANCH }}|${{ env.BRANCH }}>"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Environment* · <https://${{ env.AWS_REGION }}.console.aws.amazon.com/cloudformation/home?region=${{ env.AWS_REGION }}#/stacks/stackinfo?stackId=${{ env.WEBSITE_ARN }}|${{ env.STAGE }}>"
-                    }
-                  ]
-                },
-                {
-                  "type": "section",
-                  "text": {
-                    "type": "mrkdwn",
-                    "text": "Deployment completed with _${{ job.status }}_ ${{ env.EMOJI }}"
-                  }
-                },
-                {
-                  "type": "actions",
-                  "elements": [
-                    {
-                      "type": "button",
-                      "text": {
-                        "type": "plain_text",
-                        "text": "Preview",
-                        "emoji": true
-                      },
-                      "style": "primary",
-                      "value": "preview",
-                      "url": "http://${{ env.WEBSITE_DNS }}"
-                    },
-                    {
-                      "type": "button",
-                      "text": {
-                        "type": "plain_text",
-                        "text": "Inspect Logs",
-                        "emoji": true
-                      },
-                      "value": "inspect_logs",
-                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-                    }
-                  ]
-                }
-              ]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+      # - name: Notify slack
+      #   if: ${{ success() || failure() }}
+      #   uses: slackapi/slack-github-action@v1.18.0
+      #   with:
+      #     payload: |
+      #       {
+      #         "blocks": [
+      #           {
+      #             "type": "header",
+      #             "text": {
+      #               "type": "plain_text",
+      #               "text": ":construction: Development Deployment → :space_invader: Casimir"
+      #             }
+      #           },
+      #           {
+      #             "type": "section",
+      #             "fields": [
+      #               {
+      #                 "type": "mrkdwn",
+      #                 "text": "*Branch* · <https://github.com/${{ github.repository }}/tree/${{ env.BRANCH }}|${{ env.BRANCH }}>"
+      #               },
+      #               {
+      #                 "type": "mrkdwn",
+      #                 "text": "*Environment* · <https://${{ env.AWS_REGION }}.console.aws.amazon.com/cloudformation/home?region=${{ env.AWS_REGION }}#/stacks/stackinfo?stackId=${{ env.WEBSITE_ARN }}|${{ env.STAGE }}>"
+      #               }
+      #             ]
+      #           },
+      #           {
+      #             "type": "section",
+      #             "text": {
+      #               "type": "mrkdwn",
+      #               "text": "Deployment completed with _${{ job.status }}_ ${{ env.EMOJI }}"
+      #             }
+      #           },
+      #           {
+      #             "type": "actions",
+      #             "elements": [
+      #               {
+      #                 "type": "button",
+      #                 "text": {
+      #                   "type": "plain_text",
+      #                   "text": "Preview",
+      #                   "emoji": true
+      #                 },
+      #                 "style": "primary",
+      #                 "value": "preview",
+      #                 "url": "http://${{ env.WEBSITE_DNS }}"
+      #               },
+      #               {
+      #                 "type": "button",
+      #                 "text": {
+      #                   "type": "plain_text",
+      #                   "text": "Inspect Logs",
+      #                   "emoji": true
+      #                 },
+      #                 "value": "inspect_logs",
+      #                 "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      #               }
+      #             ]
+      #           }
+      #         ]
+      #       }
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
